version: '3.1'
services:
  pg:
    image: "postgres:12"
    container_name: "dybi-postgres"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - dybi-pg:/var/lib/postgresql/data

  pg-admin:
    image: "dpage/pgadmin4"
    container_name: "dybi-postgres-admin"
    restart: always
    ports:
      - 8088:80
    environment:
      PGADMIN_DEFAULT_EMAIL: "github@igorilic.net"
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}

volumes:
  dybi-pg:
    external: true
